/**
 * Convert a SwiftPM target or package name into its module name.
 *
 * @param {String} name Target or package name
 * @returns {String} Module name
 */
export declare function toModuleName(name: string): string;
/**
 * Decide whether a module belongs to tests or to an aggregate product and so
 * must not contribute build symbols or semantic context.
 *
 * @param {String} moduleName Module name
 * @returns {boolean} `true` when the module should be skipped
 */
export declare function isTestOrAggregateModule(moduleName: string): boolean;
/**
 * Determine the extra environment variables needed to make sourcekitten use
 * the same Swift toolchain that will build the project.
 *
 * sourcekitten resolves SourceKit through `xcrun`, so without guidance it uses
 * the active Xcode toolchain even when `swift` comes from swiftly or another
 * `.xctoolchain`. Indexing then fails with errors such as `module compiled
 * with Swift 6.4 cannot be imported by the Swift 6.1 compiler` or
 * `unknown argument`. The toolchain identifier is passed via `TOOLCHAINS`; an
 * explicitly configured `TOOLCHAINS`/`DEVELOPER_DIR` always wins.
 *
 * @returns {undefined|Object} Environment overrides for sourcekitten or undefined.
 */
export declare function sourcekittenToolchainEnv(): undefined | Object;
/**
 * Retrieve the structure information of a .swift file in json format
 *
 * @param {String} filePath Path to .swift file
 *
 * @returns {undefined|Object} JSON representation of the swift file or undefined.
 */
export declare function getStructure(filePath: string): undefined | Object; /**
 * Parse the data from the structure command
 *
 * @param {Object} structureJson Json from the structure command
 * @returns {Object|undefined} Parsed value
 */
export declare function parseStructure(structureJson: any): {
    referredTypes: any[];
} | undefined;
/**
 * Method to perform swift build in verbose mode.
 *
 * @param {String} basePath Path
 * @returns {undefined|String} Verbose build output
 */
export declare function verboseBuild(basePath: string): undefined | string;
/**
 * Method to parse the verbose swift build output to identify key compiler parameters.
 *
 * @param {String} buildOutput Verbose build output
 * @returns {Object} compiler build parameters
 */
export declare function extractCompilerParamsFromBuild(buildOutput: string): Object;
/**
 * Method to index a swift file and extract metadata
 *
 * @param {String} filePath Path to .swift file
 * @param {String|Array<string>} compilerArgs Compiler arguments extracted from verbose build log
 * @returns {undefined|Object} metadata
 */
export declare function index(filePath: string, compilerArgs: string | Array<string>): undefined | Object;
/**
 * Parse the data from the index command
 *
 * @param {Object} indexJson Json from the index command
 * @returns {Object|undefined} Parsed value
 */
export declare function parseIndex(indexJson: Object): Object | undefined;
/**
 * Method to execute dump-package package command.
 *
 * @param {String} basePath Path
 * @returns {undefined|Object} Output from dump-package command
 */
export declare function dumpPackage(basePath: string): undefined | Object;
/**
 * Parse the data from dump-package command
 *
 * @param {Object} dumpJson Json from dump-package command
 * @returns {Object|undefined} Parsed value
 */
export declare function parseDumpPackage(dumpJson: Object): Object | undefined;
/**
 * Retrieve the module information of the swift project
 *
 * @param {String} moduleName Module name
 * @param {String|Array<string>} compilerArgs Compiler arguments extracted from verbose build log
 * @returns {undefined|Object} JSON representation of the swift module or undefined.
 */
export declare function moduleInfo(moduleName: string, compilerArgs: string | Array<string>): undefined | Object;
/**
 * Parse the data from module-info command to replicate the swift interface
 *
 * @param {Object} moduleInfoJson Json from module-info command
 * @returns {Object|undefined} Parsed classes, protocols, enums and their functions
 */
export declare function parseModuleInfo(moduleInfoJson: Object): Object | undefined;
/**
 * Method to collect the build symbols from the output file maps generated by
 * swift build.
 *
 * Both build engines are supported: the classic llbuild backend (default until
 * Swift 6.3) writes per-module `output-file-map.json` files, while the Swift
 * Build engine (default from Swift 6.4/Xcode 27) writes per-target
 * `<target>-OutputFileMap.json` files under `.build/out/Intermediates.noindex`.
 *
 * @param {String} basePath Path
 * @param {Object} options CLI options
 * @returns {Object} symbols map keyed by module name
 */
export declare function collectBuildSymbols(basePath: string, options: Object): Object;
/**
 * Method to parse output file map to identify the module and their symbols.
 * This list is imprecise when compared with the data from module-info command.
 *
 * The module name is derived from the containing directory for llbuild maps
 * (`<Module>.build` and, since Swift 6.4, `<Module>-tool.build`) and from the
 * file name for Swift Build maps (`<target>-OutputFileMap.json`, where the
 * target name still needs to be sanitised into a module name).
 *
 * @param filemap {String} File name
 * @returns {Object} parsed module metadata
 */
export declare function parseOutputFileMap(filemap: string): Object;
/**
 * Parse the Swift Build manifest (`manifest.pif`) emitted by the Swift Build
 * engine under `.build/`.
 *
 * The manifest is a list of workspace, project, and target objects linked
 * through their `signature` hashes. Project objects carry the package
 * identity (`PACKAGE:<identity>` guid) and the Package.swift path, while
 * target objects record the exact `PRODUCT_MODULE_NAME`. This is the only
 * artifact that maps the modules built from a dependency checkout back to its
 * package identity without re-running `swift package dump-package`.
 *
 * @param {Array} manifestJson Parsed manifest.pif contents
 * @returns {undefined|Object} `{ packageModules }` keyed by package aliases or undefined.
 */
export declare function parseSwiftBuildManifest(manifestJson: any[]): undefined | Object;
/**
 * Parse a `Package.resolved` document (both v1 `object.pins` and the current
 * `pins` shapes) into a lookup of dependency identities and repository names.
 *
 * @param resolvedJson {Object} Parsed Package.resolved contents
 * @returns {Object} `{ aliases }` mapping every known package alias to the identity
 */
export declare function parseSwiftResolvedAliases(resolvedJson: Object): Object;
/**
 * Build a package name/identity to module names map for the workspace.
 *
 * The Swift Build engine exposes the mapping directly through `manifest.pif`;
 * for the llbuild engine the map is assembled from `swift package
 * dump-package` of the root package and of every dependency checkout.
 *
 * @param {String} basePath Path
 * @param {Object} options CLI options
 * @param {Object} rootPackageMetadata Parsed dump-package metadata of the root package
 * @returns {Object} Map of package aliases to module names
 */
export declare function collectPackageModules(basePath: string, options: Object, rootPackageMetadata: Object): Object;
/**
 * Point the given compiler arguments at a scratch module cache.
 *
 * The build's own `-module-cache-path` is shared with every compiler
 * invocation that ever touched the project, including other toolchains, and a
 * cache holding modules from a mismatched Swift version makes sourcekitten
 * silently return empty module interfaces. A private cache per evinse run
 * avoids that poisoning at the cost of rebuilding the SDK clang modules once.
 *
 * @param {Array<String>} compilerArgs Compiler arguments
 * @returns {Array<String>} Compiler arguments with an isolated module cache
 */
export declare function withFreshModuleCache(compilerArgs: Array<string>): Array<string>;
/**
 * Create a precise semantics slices file for a swift project.
 *
 * @param basePath basePath Path
 * @param options options CLI options
 */
export declare function createSemanticsSlices(basePath: any, options: any): {
    packageMetadata: Object | undefined;
    packageModules: Object;
    buildSymbols: Object;
    moduleInfos: {};
    fileStructures: {};
    fileIndexes: {};
} | undefined;
//# sourceMappingURL=swiftsem.d.ts.map